// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BCJ8ZkuS_dEIDlCeDMWvtKzidy0oKZE',
    appId: '1:570191014591:web:36dadc99efe80759cd340a',
    messagingSenderId: '570191014591',
    projectId: 'mobilehealthcarecheck',
    authDomain: 'mobilehealthcarecheck.firebaseapp.com',
    storageBucket: 'mobilehealthcarecheck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwCJr5m9uy-26yCm4frUZFD5bE4NTrcyk',
    appId: '1:570191014591:android:518802ba628cc9dacd340a',
    messagingSenderId: '570191014591',
    projectId: 'mobilehealthcarecheck',
    storageBucket: 'mobilehealthcarecheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtu9Um3tl5HdY4cKURVnlzpYSeJHFyZk',
    appId: '1:570191014591:ios:8ddcc6f53ce654d2cd340a',
    messagingSenderId: '570191014591',
    projectId: 'mobilehealthcarecheck',
    storageBucket: 'mobilehealthcarecheck.appspot.com',
    iosClientId: '570191014591-5q2css210dfvr2j87f9fmae1f9sil341.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileHealthCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmtu9Um3tl5HdY4cKURVnlzpYSeJHFyZk',
    appId: '1:570191014591:ios:8ddcc6f53ce654d2cd340a',
    messagingSenderId: '570191014591',
    projectId: 'mobilehealthcarecheck',
    storageBucket: 'mobilehealthcarecheck.appspot.com',
    iosClientId: '570191014591-5q2css210dfvr2j87f9fmae1f9sil341.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileHealthCheck',
  );
}